### PR TITLE
Post Collaborative Coding update

### PR DESCRIPTION
**Pull request by PythonJedi**
- Upload pdf of git slides
- Update post with links to slides, git book, github help, and gitlab documentation

### CODE REVIEW

**Comment by m-wynn** [comment]
I believe the href elements should have quotation marks around them.
https://www.w3.org/TR/REC-html40/intro/sgmltut.html#h-3.2.2

**Comment by m-wynn** [comment]
Actually, since this is jekyll, use markdown syntax.  i.e. https://raw.githubusercontent.com/utdlug/utdlug.github.io/master/_posts/2014-03-25-amazon-web-services-meeting.md

**Comment by PythonJedi** [comment]
Was following example set in cryptoparty and linux jeopardy, will fix.

**Comment by m-wynn** [comment]
Yes, those are wrong too.

**Comment by PythonJedi** [comment]
Will add issues for them, is there anything else that needs to be modified?

**Comment by m-wynn** [comment]
That looks good!  Could you rebase your commits so that "Fix Link Syntax" is fixup'd into the "Update Collaborative Coding" commit?

**Comment by PythonJedi** [comment]
That would require making a placeholder branch, moving master back, and then rebasing, correct?

**Comment by m-wynn** [comment]
Ideally, you would have done all this on a branch and then you could `git rebase -i master`.  However, I believe you could get away with `git rebase -i HEAD~3`.

**Comment by PythonJedi** [comment]
Yeah, derped there. working on not doing that for the other ones.

**Comment by m-wynn** [comment]
Jekyll needs a newline between the content and the bullet points, or else it will look like this.

Ignore the fact it says merged.  It's not.

**Comment by PythonJedi** [comment]
will move off into branch. working on #8 right now

**Comment by m-wynn** [comment]
Works good now!

**Pull request merged**
